// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._Shitmed.UserInterface.Systems.Targeting.Widgets;

[GenerateTypedNameReferences]
public sealed partial class TargetingControl : UIWidget
{
    private readonly TargetingUIController _controller;
    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
    private TargetBodyPart _currentPart = TargetBodyPart.Chest;

    // Navigation map: [current] -> (Up, Down, Left, Right) — null means no movement in that direction
    private static readonly Dictionary<TargetBodyPart, (TargetBodyPart? Up, TargetBodyPart? Down, TargetBodyPart? Left, TargetBodyPart? Right)> _navMap = new()
    {
        { TargetBodyPart.Head,      (null,                   TargetBodyPart.Chest,    null,                   null)                   },
        { TargetBodyPart.Chest,     (TargetBodyPart.Head,    TargetBodyPart.Groin,    TargetBodyPart.LeftArm, TargetBodyPart.RightArm)},
        { TargetBodyPart.Groin,     (TargetBodyPart.Chest,   null,                   TargetBodyPart.LeftLeg, TargetBodyPart.RightLeg)},
        { TargetBodyPart.LeftArm,   (null,                   TargetBodyPart.LeftHand, TargetBodyPart.Chest,  null)                   },
        { TargetBodyPart.LeftHand,  (TargetBodyPart.LeftArm, null,                   null,                   null)                   },
        { TargetBodyPart.RightArm,  (null,                   TargetBodyPart.RightHand,null,                  TargetBodyPart.Chest)   },
        { TargetBodyPart.RightHand, (TargetBodyPart.RightArm,null,                   null,                   null)                   },
        { TargetBodyPart.LeftLeg,   (TargetBodyPart.Groin,   TargetBodyPart.LeftFoot, TargetBodyPart.Groin,  null)                   },
        { TargetBodyPart.LeftFoot,  (TargetBodyPart.LeftLeg, null,                   null,                   null)                   },
        { TargetBodyPart.RightLeg,  (TargetBodyPart.Groin,   TargetBodyPart.RightFoot,null,                  TargetBodyPart.Groin)   },
        { TargetBodyPart.RightFoot, (TargetBodyPart.RightLeg,null,                   null,                   null)                   },
    };

    public TargetingControl()
    {
        RobustXamlLoader.Load(this);
        _controller = UserInterfaceManager.GetUIController<TargetingUIController>();

        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            // TODO: ADD EYE AND MOUTH TARGETING
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton },
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key);

        }

        BackgroundSprite.SetFromSpriteSpecifier(new Robust.Shared.Utility.SpriteSpecifier.Rsi(new Robust.Shared.Utility.ResPath("/Textures/Interface/Hud/zone_sel.rsi"), "base"));
        BackgroundSprite.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (!_navMap.TryGetValue(_currentPart, out var nav))
            return;

        TargetBodyPart? next = null;

        if (args.Function == EngineKeyFunctions.TextCursorUp)
            next = nav.Up;
        else if (args.Function == EngineKeyFunctions.TextCursorDown)
            next = nav.Down;
        else if (args.Function == EngineKeyFunctions.TextCursorLeft)
            next = nav.Left;
        else if (args.Function == EngineKeyFunctions.TextCursorRight)
            next = nav.Right;

        if (next.HasValue)
        {
            args.Handle();
            SetActiveBodyPart(next.Value);
        }
    }

    private void SetActiveBodyPart(TargetBodyPart bodyPart)
    {
        _currentPart = bodyPart;
        _controller.CycleTarget(bodyPart);
    }

    public void SetBodyPartsVisible(TargetBodyPart bodyPart)
    {
        _currentPart = bodyPart;
        foreach (var bodyPartButton in _bodyPartControls)
            bodyPartButton.Value.Children.First().Visible = bodyPartButton.Key == bodyPart;
    }

    protected override void OnThemeUpdated() {}

    public void SetTargetDollVisible(bool visible) => Visible = visible;

}