using Content.Shared._NigWeb.Lifeweb;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._NigWeb.Lifeweb
{
    [GenerateTypedNameReferences]
    public sealed partial class LifewebControlWindow : DefaultWindow
    {
        public LifewebControlWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateState(LifewebControlBuiState state)
        {
            if (state.Mode == 1)
            {
                StatusLabel.Text = "Статус: АКТИВЕН (Выкачивание: ЛИБИДО)";
                StatusLabel.FontColorOverride = Color.LimeGreen;
            }
            else if (state.Mode == 2)
            {
                StatusLabel.Text = "Статус: АКТИВЕН (Выкачивание: МОРТИДО)";
                StatusLabel.FontColorOverride = Color.Purple;
            }
            else
            {
                StatusLabel.Text = "Статус: ОЖИДАНИЕ";
                StatusLabel.FontColorOverride = Color.Red;
            }
            
            PowerLabel.Text = $"{state.PowerOutput} Вт";
            ChargeLabel.Text = $"{(int)state.BatteryCharge} / {(int)state.BatteryMaxCharge}";
        }
    }
}
