// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Shared.IoC;

namespace Content.Client._Shitcode.UserActions;

[GenerateTypedNameReferences]
public sealed partial class UserActionsPanel : Control
{
    private UserActionUIController _controller;

    public UserActionsPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _controller = UserInterfaceManager.GetUIController<UserActionUIController>();
        _controller.RegisterPanel(this);

        var resCache = IoCManager.Resolve<IResourceCache>();
        MainPanel.PanelOverride = new StyleBoxTexture
        {
            Texture = resCache.GetResource<TextureResource>("/Textures/Interface/Nano/lfwb_chat_panel.png").Texture,
            Mode = StyleBoxTexture.StretchMode.Tile
        };

        RegisterTabs();
    }

    private void RegisterTabs()
    {
        _controller.RegisterTab(EmotesTabControl);
    }

    public void UpdateTabs()
    {
        var anyVisible = false;

        foreach (var tab in _controller.GetTabs())
        {
            var visible = tab.UpdateState();
            tab.Visible = visible;

            if (visible)
                anyVisible = true;
        }

        MainPanel.Visible = true;
        NoContentLabel.Visible = !anyVisible;
    }
}
